### ISSUE TITLE
UrlSearchParam is not a constructor

### ISSUE THREAD

**Issue by vocasle** [Soontao/c4codata#5]
When adding `$expand` query parameter to the request I'm getting the following error:
`UrlSearchParam is not a constructor`

Error points to `var rt = new UrlSearchParam();` in `params.js` in `c4codata/lib/params.js`
If I change `var UrlSearchParam = require("@ungap/url-search-params");` to 
`var UrlSearchParam = require("@ungap/url-search-params").default;` the error goes away.

Do not know if the problem is in the c4codata itself or in my config (I am using Create React App with TypeScript 3.5.1)

**Comment by Soontao** [comment]
Hi @vocasle, 

I'm not sure what happened because all unit tests are passed, but I guess that was caused by different module system (js/ts), so I switch on the `esModuleInterop` and `allowSyntheticDefaultImports` indicators to enchance the typesystem compatibility.

Please re-test your code in the new version`v1.4.1`.

**Comment by vocasle** [comment]
Hi @Soontao,
`v1.4.1` fixed the issue.
